export const SCREENS = {
    INTRO: 'INTRO',
    REG_1: 'REG_1',
    REG_2: 'REG_2',
    LOGIN: 'LOGIN',
    LOBBY: 'LOBBY',
    GAME1: 'GAME1',
    POST_GAME1: 'POST_GAME1',
    GAME2: 'GAME2',
    POST_GAME2: 'POST_GAME2',
    GAME3: 'GAME3',
    POST_GAME3: 'POST_GAME3',
    GAME4: 'GAME4',
    POST_GAME4: 'POST_GAME4',
    LIBRARY: 'LIBRARY',
    FINISH: 'FINISH',
}

export const NEXT_SCREENS = {
    [SCREENS.INTRO]: null,
    [SCREENS.REG_1]: SCREENS.REG_2,
    [SCREENS.REG_2]: SCREENS.LOBBY,
    [SCREENS.LOGIN]: SCREENS.LOBBY,
    [SCREENS.LOBBY]: SCREENS.GAME1,
    [SCREENS.GAME1]: SCREENS.POST_GAME1,
    [SCREENS.GAME2]: SCREENS.POST_GAME2,
    [SCREENS.GAME3]: SCREENS.POST_GAME3,
    [SCREENS.GAME4]: SCREENS.POST_GAME4,
}
